batch_size: 16
num_gpus: 1
exponential_decay: True
learning_rate: 0.01
learning_rate_decay: 0.95
learning_rate_decay_steps: 2000
max_steps: 2000000






#start_learning_rate: 0.005
#end_learning_rate: 0.00000001
#learning_power: 4.0